name: todo_app
description: A modern todo application built with Flutter
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  uuid: ^4.2.1
  intl: ^0.19.0
  image_picker: ^1.0.4
  month_picker_dialog: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/clock-icon.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/icon/clock-icon.png"
    icon_size: 48 